from pomegranate import *

Demanda= Node(DiscreteDistribution({
    "Pc Gamer": 0.6,
    "Television 4K": 0.4,
    "Telefono": 0.7,
    "Tablet": 0.4,
    "Consola de videojuegos": 0.8,
    "Refrigerador": 0.5,
    "Lavadora": 0.7,
    "Secadora": 0.6,
    "Estufa": 0.3,
    "Microondas": 0.9,
    "Tostadora": 0.7,
    "Cafetera": 0.4,
    "Licuadora": 0.8,
    "Procesadora de alimentos": 0.5,
    "Batidora": 0.6,
    "Aspiradora": 0.3,
    "Ventilador": 0.7,
    "Aire acondicionado": 0.9,
    "Calefactor": 0.8,
    "Humidificador": 0.4,
    "Deshumidificador": 0.5,
    "Purificador de aire": 0.6,
    "Silla de escritorio": 0.7,
    "Mesa de escritorio": 0.8,
    "Lampara": 0.9,
    "Archivador": 0.4,
    "Papelera": 0.6,
    "Caja de herramientas": 0.3,
    "Escalera": 0.8,
    "Botiquin": 0.7
}), name="Demanda")

Unidades = Node(DiscreteDistribution({
    "Muchas unidades": 0.6,
    "Unidades promedio": 0.3,
    "Pocas unidades":0.1
}), name="Unidades")

# Nodo de Mantenimiento esta condicionado por la lluvia
Disponibilidad= Node(ConditionalProbabilityTable([
    ["Pc Gamer", "Muchas unidades","Disponible" ,0.9],
    ["Pc Gamer", "Muchas unidades","NoDisponible" ,0.1],
    ["Pc Gamer", "Unidades promedio","Disponible" ,0.7],
    ["Pc Gamer", "Unidades promedio","NoDisponible" ,0.3],
    ["Pc Gamer", "Pocas unidades","Disponible" ,0.4],
    ["Pc Gamer", "Pocas unidades","NoDisponible" ,0.6],
    ["Television 4K", "Muchas unidades","Disponible" ,0.9],
    ["Television 4K", "Muchas unidades","NoDisponible" ,0.1],
    ["Television 4K", "Unidades promedio","Disponible" ,0.7],
    ["Television 4K", "Unidades promedio","NoDisponible" ,0.3],
    ["Television 4K", "Pocas unidades","Disponible" ,0.4],
    ["Television 4K", "Pocas unidades","NoDisponible" ,0.6],
    ["Telefono", "Muchas unidades","Disponible", 0.9],
    ["Telefono", "Muchas unidades","NoDisponible", 0.1],
    ["Telefono", "Unidades promedio", "Disponible",0.7],
    ["Telefono", "Unidades promedio","NoDisponible" , 0.3],
    ["Telefono", "Pocas unidades", "Disponible" , 0.4],
    ["Telefono", "Pocas unidades","NoDisponible" , 0.6],
    ["Tablet", "Muchas unidades", "Disponible", 0.8],
    ["Tablet", "Muchas unidades", "NoDisponible", 0.2],
    ["Tablet", "Unidades promedio", "Disponible", 0.6],
    ["Tablet", "Unidades promedio", "NoDisponible", 0.4],
    ["Tablet", "Pocas unidades", "Disponible", 0.3],
    ["Tablet", "Pocas unidades", "NoDisponible", 0.7],
    ["Consola de videojuegos", "Muchas unidades", "Disponible", 0.85],
    ["Consola de videojuegos", "Muchas unidades", "NoDisponible", 0.15],
    ["Consola de videojuegos", "Unidades promedio", "Disponible", 0.65],
    ["Consola de videojuegos", "Unidades promedio", "NoDisponible", 0.35],
    ["Consola de videojuegos", "Pocas unidades", "Disponible", 0.25],
    ["Consola de videojuegos", "Pocas unidades", "NoDisponible", 0.75],
    ["Refrigerador", "Muchas unidades", "Disponible", 0.9],
    ["Refrigerador", "Muchas unidades", "NoDisponible", 0.1],
    ["Refrigerador", "Unidades promedio", "Disponible", 0.7],
    ["Refrigerador", "Unidades promedio", "NoDisponible", 0.3],
    ["Refrigerador", "Pocas unidades", "Disponible", 0.4],
    ["Refrigerador", "Pocas unidades", "NoDisponible", 0.6],
    ["Lavadora", "Muchas unidades", "Disponible", 0.8],
    ["Lavadora", "Muchas unidades", "NoDisponible", 0.2],
    ["Lavadora", "Unidades promedio", "Disponible", 0.6],
    ["Lavadora", "Unidades promedio", "NoDisponible", 0.4],
    ["Lavadora", "Pocas unidades", "Disponible", 0.3],
    ["Lavadora", "Pocas unidades", "NoDisponible", 0.7],
    ["Secadora", "Muchas unidades", "Disponible", 0.85],
    ["Secadora", "Muchas unidades", "NoDisponible", 0.15],
    ["Secadora", "Unidades promedio", "Disponible", 0.65],
    ["Secadora", "Unidades promedio", "NoDisponible", 0.35],
    ["Secadora", "Pocas unidades", "Disponible", 0.25],
    ["Secadora", "Pocas unidades", "NoDisponible", 0.75],
    ["Estufa", "Muchas unidades", "Disponible", 0.9],
    ["Estufa", "Muchas unidades", "NoDisponible", 0.1],
    ["Estufa", "Unidades promedio", "Disponible", 0.7],
    ["Estufa", "Unidades promedio", "NoDisponible", 0.3],
    ["Estufa", "Pocas unidades", "Disponible", 0.4],
    ["Estufa", "Pocas unidades", "NoDisponible", 0.6],
    ["Microondas", "Muchas unidades", "Disponible", 0.8],
    ["Microondas", "Muchas unidades", "NoDisponible", 0.2],
    ["Microondas", "Unidades promedio", "Disponible", 0.6],
    ["Microondas", "Unidades promedio", "NoDisponible", 0.4],
    ["Microondas", "Pocas unidades", "Disponible", 0.3],
    ["Microondas", "Pocas unidades", "NoDisponible", 0.7],
    ["Tostadora", "Muchas unidades", "Disponible", 0.85],
    ["Tostadora", "Muchas unidades", "NoDisponible", 0.15],
    ["Tostadora", "Unidades promedio", "Disponible", 0.65],
    ["Tostadora", "Unidades promedio", "NoDisponible", 0.35],
    ["Tostadora", "Pocas unidades", "Disponible", 0.25],
    ["Tostadora", "Pocas unidades", "NoDisponible", 0.75],
    ["Cafetera", "Muchas unidades", "Disponible", 0.9],
    ["Cafetera", "Muchas unidades", "NoDisponible", 0.1],
    ["Cafetera", "Unidades promedio", "Disponible", 0.7],
    ["Cafetera", "Unidades promedio", "NoDisponible", 0.3],
    ["Cafetera", "Pocas unidades", "Disponible", 0.4],
    ["Cafetera", "Pocas unidades", "NoDisponible", 0.6],
    ["Licuadora", "Muchas unidades", "Disponible", 0.8],
    ["Licuadora", "Muchas unidades", "NoDisponible", 0.2],
    ["Licuadora", "Unidades promedio", "Disponible", 0.6],
    ["Licuadora", "Unidades promedio", "NoDisponible", 0.4],
    ["Licuadora", "Pocas unidades", "Disponible", 0.3],
    ["Licuadora", "Pocas unidades", "NoDisponible", 0.7],
    ["Procesadora de alimentos", "Muchas unidades", "Disponible", 0.85],
    ["Procesadora de alimentos", "Muchas unidades", "NoDisponible", 0.15],
    ["Procesadora de alimentos", "Unidades promedio", "Disponible", 0.65],
    ["Procesadora de alimentos", "Unidades promedio", "NoDisponible", 0.35],
    ["Procesadora de alimentos", "Pocas unidades", "Disponible", 0.25],
    ["Procesadora de alimentos", "Pocas unidades", "NoDisponible", 0.75],
    ["Batidora", "Muchas unidades", "Disponible", 0.9],
    ["Batidora", "Muchas unidades", "NoDisponible", 0.1],
    ["Batidora", "Unidades promedio", "Disponible", 0.7],
    ["Batidora", "Unidades promedio", "NoDisponible", 0.3],
    ["Batidora", "Pocas unidades", "Disponible", 0.4],
    ["Batidora", "Pocas unidades", "NoDisponible", 0.6],
    ["Aspiradora", "Muchas unidades", "Disponible", 0.8],
    ["Aspiradora", "Muchas unidades", "NoDisponible", 0.2],
    ["Aspiradora", "Unidades promedio", "Disponible", 0.6],
    ["Aspiradora", "Unidades promedio", "NoDisponible", 0.4],
    ["Aspiradora", "Pocas unidades", "Disponible", 0.3],
    ["Aspiradora", "Pocas unidades", "NoDisponible", 0.7],
    ["Ventilador", "Muchas unidades", "Disponible", 0.85],
    ["Ventilador", "Muchas unidades", "NoDisponible", 0.15],
    ["Ventilador", "Unidades promedio", "Disponible", 0.65],
    ["Ventilador", "Unidades promedio", "NoDisponible", 0.35],
    ["Ventilador", "Pocas unidades", "Disponible", 0.25],
    ["Ventilador", "Pocas unidades", "NoDisponible", 0.75],
    ["Aire acondicionado", "Muchas unidades", "Disponible", 0.9],
    ["Aire acondicionado", "Muchas unidades", "NoDisponible", 0.1],
    ["Aire acondicionado", "Unidades promedio", "Disponible", 0.7],
    ["Aire acondicionado", "Unidades promedio", "NoDisponible", 0.3],
    ["Aire acondicionado", "Pocas unidades", "Disponible", 0.4],
    ["Aire acondicionado", "Pocas unidades", "NoDisponible", 0.6],
    ["Calefactor", "Muchas unidades", "Disponible", 0.8],
    ["Calefactor", "Muchas unidades", "NoDisponible", 0.2],
    ["Calefactor", "Unidades promedio", "Disponible", 0.6],
    ["Calefactor", "Unidades promedio", "NoDisponible", 0.4],
    ["Calefactor", "Pocas unidades", "Disponible", 0.3],
    ["Calefactor", "Pocas unidades", "NoDisponible", 0.7],
    ["Humidificador", "Muchas unidades", "Disponible", 0.85],
    ["Humidificador", "Muchas unidades", "NoDisponible", 0.15],
    ["Humidificador", "Unidades promedio", "Disponible", 0.65],
    ["Humidificador", "Unidades promedio", "NoDisponible", 0.35],
    ["Humidificador", "Pocas unidades", "Disponible", 0.25],
    ["Humidificador", "Pocas unidades", "NoDisponible", 0.75],
    ["Deshumidificador", "Muchas unidades", "Disponible", 0.9],
    ["Deshumidificador", "Muchas unidades", "NoDisponible", 0.1],
    ["Deshumidificador", "Unidades promedio", "Disponible", 0.7],
    ["Deshumidificador", "Unidades promedio", "NoDisponible", 0.3],
    ["Deshumidificador", "Pocas unidades", "Disponible", 0.4],
    ["Deshumidificador", "Pocas unidades", "NoDisponible", 0.6],
    ["Purificador de aire", "Muchas unidades", "Disponible", 0.8],
    ["Purificador de aire", "Muchas unidades", "NoDisponible", 0.2],
    ["Purificador de aire", "Unidades promedio", "Disponible", 0.6],
    ["Purificador de aire", "Unidades promedio", "NoDisponible", 0.4],
    ["Purificador de aire", "Pocas unidades", "Disponible", 0.3],
    ["Purificador de aire", "Pocas unidades", "NoDisponible", 0.7],
    ["Silla de escritorio", "Muchas unidades", "Disponible", 0.85],
    ["Silla de escritorio", "Muchas unidades", "NoDisponible", 0.15],
    ["Silla de escritorio", "Unidades promedio", "Disponible", 0.65],
    ["Silla de escritorio", "Unidades promedio", "NoDisponible", 0.35],
    ["Silla de escritorio", "Pocas unidades", "Disponible", 0.25],
    ["Silla de escritorio", "Pocas unidades", "NoDisponible", 0.75],
    ["Mesa de escritorio", "Muchas unidades", "Disponible", 0.9],
    ["Mesa de escritorio", "Muchas unidades", "NoDisponible", 0.1],
    ["Mesa de escritorio", "Unidades promedio", "Disponible", 0.7],
    ["Mesa de escritorio", "Unidades promedio", "NoDisponible", 0.3],
    ["Mesa de escritorio", "Pocas unidades", "Disponible", 0.4],
    ["Mesa de escritorio", "Pocas unidades", "NoDisponible", 0.6],
    ["Lampara", "Muchas unidades", "Disponible", 0.8],
    ["Lampara", "Muchas unidades", "NoDisponible", 0.2],
    ["Lampara", "Unidades promedio", "Disponible", 0.6],
    ["Lampara", "Unidades promedio", "NoDisponible", 0.4],
    ["Lampara", "Pocas unidades", "Disponible", 0.3],
    ["Lampara", "Pocas unidades", "NoDisponible", 0.7],
    ["Archivador", "Muchas unidades", "Disponible", 0.85],
    ["Archivador", "Muchas unidades", "NoDisponible", 0.15],
    ["Archivador", "Unidades promedio", "Disponible", 0.65],
    ["Archivador", "Unidades promedio", "NoDisponible", 0.35],
    ["Archivador", "Pocas unidades", "Disponible", 0.25],
    ["Archivador", "Pocas unidades", "NoDisponible", 0.75],
    ["Papelera", "Muchas unidades", "Disponible", 0.9],
    ["Papelera", "Muchas unidades", "NoDisponible", 0.1],
    ["Papelera", "Unidades promedio", "Disponible", 0.7],
    ["Papelera", "Unidades promedio", "NoDisponible", 0.3],
    ["Papelera", "Pocas unidades", "Disponible", 0.4],
    ["Papelera", "Pocas unidades", "NoDisponible", 0.6],
    ["Caja de herramientas", "Muchas unidades", "Disponible", 0.8],
    ["Caja de herramientas", "Muchas unidades", "NoDisponible", 0.2],
    ["Caja de herramientas", "Unidades promedio", "Disponible", 0.6],
    ["Caja de herramientas", "Unidades promedio", "NoDisponible", 0.4],
    ["Caja de herramientas", "Pocas unidades", "Disponible", 0.3],
    ["Caja de herramientas", "Pocas unidades", "NoDisponible", 0.7],
    ["Escalera", "Muchas unidades", "Disponible", 0.85],
    ["Escalera", "Muchas unidades", "NoDisponible", 0.15],
    ["Escalera", "Unidades promedio", "Disponible", 0.65],
    ["Escalera", "Unidades promedio", "NoDisponible", 0.35],
    ["Escalera", "Pocas unidades", "Disponible", 0.25],
    ["Escalera", "Pocas unidades", "NoDisponible", 0.75],
    ["Botiquin", "Muchas unidades", "Disponible", 0.9],
    ["Botiquin", "Muchas unidades", "NoDisponible", 0.1],
    ["Botiquin", "Unidades promedio", "Disponible", 0.7],
    ["Botiquin", "Unidades promedio", "NoDisponible", 0.3],
    ["Botiquin", "Pocas unidades", "Disponible", 0.4],
    ["Botiquin", "Pocas unidades", "NoDisponible", 0.6]
], [Demanda.distribution, Unidades.distribution]), name="Disponibilidad")


# Creamos una Red Bayesiana y añadimos estados
modelo = BayesianNetwork()
modelo.add_states(Demanda, Unidades, Disponibilidad)

# Añadimos bordes que conecten nodos
modelo.add_edge(Demanda, Disponibilidad)
modelo.add_edge(Unidades, Disponibilidad)


# Modelo Final
modelo.bake()

